using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Icomm.NewsCrawl.Website.Models
{
    public partial class Domain
    {
        [Key]
        public int Id { get; set; }
        [Column("Domain")]
        [StringLength(50)]
        public string Domain1 { get; set; }
        public int Type { get; set; }
        [Required]
        public string Content { get; set; }
        public string Properties { get; set; }
        public int Proxy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime UpdateTime { get; set; }
        public bool? AutoGenerated { get; set; }
        public int UpdateCount { get; set; }
        public bool IsCheck { get; set; }
    }
}
